-- Drop existing tables
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Comp3334_ShareFile';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Comp3334_AccFile';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Comp3334_LogCSS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Comp3334_CSSAccount';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE Comp3334_CSSAccount(
    accNo NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    loginName VARCHAR(20) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(30) NOT NULL,
    phoneNo NUMBER(8) NOT NULL,
    userStatus NUMBER (1) NOT NULL,
    userRight NUMBER(1) NOT NULL,
    PRIMARY KEY (accNo)
);

CREATE TABLE Comp3334_LogCSS(
    logNo NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    accNo NUMBER(10) NOT NULL,
    action VARCHAR(255) NOT NULL,
    logDate DATE NOT NULL,
    PRIMARY KEY (logNo),
	FOREIGN KEY (accNo) REFERENCES Comp3334_CSSAccount(accNo)
);

CREATE TABLE Comp3334_AccFile(
    fileNo NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY, 
    accNo NUMBER(10), 
    fileName VARCHAR(255) NOT NULL, 
    fileData BLOB NOT NULL, 
    uploadedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (fileNo),
    FOREIGN KEY (accNo) REFERENCES Comp3334_CSSAccount(accNo) 
);
CREATE TABLE Comp3334_ShareFile(
    fileNo NUMBER(10), 
    accNo NUMBER(10), 
    PRIMARY KEY (fileNo, accNo),
    FOREIGN KEY (fileNo) REFERENCES Comp3334_AccFile (fileNo),
    FOREIGN KEY (accNo) REFERENCES Comp3334_CSSAccount(accNo) 
);

-- All account password is 'x0' and the database is stored in hash, hash format: <salt:hashpwd>
-- The TOTP of 'admin' and 'user3' is same, based the hash is used on the TOTP’s SK
INSERT INTO Comp3334_CSSAccount (loginName, password, email, phoneNo, userStatus, userRight)
VALUES ('yyy', 'AAAAAAAAAAAAAAAA:4b2a26ef18dc18e1094db03c9595d615', 'yyy@connect.polyu', 12345678, 0, 0);

INSERT INTO Comp3334_CSSAccount (loginName, password, email, phoneNo, userStatus, userRight)
VALUES ('yyy2', 'BBBBBBBBBBBBBBBB:7b998d7fc375f627b4feeabb4168b071', 'yyy2@connect.polyu', 64578923, 0, 0);

INSERT INTO Comp3334_CSSAccount (loginName, password, email, phoneNo, userStatus, userRight)
VALUES ('user3', 'CCCCCCCCCCCCCCCC:70a3cd8dbf9f184814d788e73860e030', 'user3@connect.polyu', 45678921, 0, 0);

INSERT INTO Comp3334_CSSAccount (loginName, password, email, phoneNo, userStatus, userRight)
VALUES ('badacc', 'BBBBBBBBBBBBBBBB:7b998d7fc375f627b4feeabb4168b071', 'badacc@connect.polyu', 87654321, 1, 0);

INSERT INTO Comp3334_CSSAccount (loginName, password, email, phoneNo, userStatus, userRight)
VALUES ('admin', 'CCCCCCCCCCCCCCCC:70a3cd8dbf9f184814d788e73860e030', '22027226d@connect.polyu.hk', 56635210, 0, 1);

INSERT INTO Comp3334_AccFile (accNo, fileName, fileData)
VALUES (1, 'report.pdf', EMPTY_BLOB());

INSERT INTO Comp3334_AccFile (accNo, fileName, fileData)
VALUES (1, 'report2.pdf', EMPTY_BLOB()); 

INSERT INTO Comp3334_AccFile (accNo, fileName, fileData)
VALUES (2, 'yyy2_testreport1.pdf', EMPTY_BLOB());

INSERT INTO Comp3334_AccFile (accNo, fileName, fileData)
VALUES (2, 'yyy2_testreport2.pdf', EMPTY_BLOB()); 

INSERT INTO Comp3334_ShareFile (fileNo, accNo)
VALUES (1, 2); 

INSERT INTO Comp3334_ShareFile (fileNo, accNo)
VALUES (1, 3); 

INSERT INTO Comp3334_ShareFile (fileNo, accNo)
VALUES (4, 1); 

commit;
